(library
 (name fastsearch_plugin)
 (public_name coq-fastsearch.plugin)
 (flags :standard -rectypes -w -27)
 (libraries
  coq-core.vernac
  coq-core.library
  coq-core.engine
  coq-core.kernel
  coq-core.lib
  coq-core.pretyping
  coq-core.interp
  coq-core.printing
  coq-core.parsing
  coq-core.gramlib
  coq-core.plugins.ltac))
